#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

source ${OPENSHIFT_DATA_DIR}/setenv.sh

cd $OPENSHIFT_REPO_DIR
nohup java -jar java-backend/target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} > ${OPENSHIFT_LOG_DIR}/cobone-reviews.log &
